/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package similarity;

import org.junit.Test;

public class AppTest {
	@Test
	public void testAppHasAGreeting() {
		SimilarityCalculator classUnderTest = new SimilarityCalculator();
		
	}
}
